"""Kokoro-82M narration, one scene at a time, with measured per-sentence timings.

The model files and their URLs are the ones the MoneyPrinterTurbo fork pins (app/services/voice.py, KOKORO_MODEL_URL
and KOKORO_VOICES_URL: release assets of thewh1teagle/kokoro-onnx, tag model-files-v1.0). The fork records no hash,
so the sha256 values below were measured on the first download here (27.9.2026) and then matched against
independent pins of the same URLs on GitHub — e.g. nordwestt/kokoro-wyoming's Dockerfile
(`ADD --checksum=sha256:7d5d...` / `sha256:bca6...`) — found by code search. Nothing is fetched from anywhere else.

Licences (fork notes, reused as stated there): weights Apache-2.0, kokoro-onnx MIT; phonemisation goes through
espeak-ng / phonemizer (GPL-3.0), which governs redistributing those libraries, not the audio they help make.
Provenance note that travels with the channel (RED-TEAM §2.12): the model card records training on "synthetic audio
generated by closed TTS models from large providers" [research/rendered/kokoro-82m-model-card-2026-09-29.txt:241,
the dated frozen copy; the live capture's lines move with each render].

Synthesis follows the fork's fixed path (commit 23397c8): whole sentences, punctuation kept, English numbers spelled
out before phonemisation while the written text keeps the figures.
"""

from __future__ import annotations

import re
import wave
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

import numpy as np

from fetch import CACHE_DIR, fetch


@dataclass(frozen=True)
class ModelFile:
    filename: str
    url: str
    sha256: str


_RELEASE = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0"
KOKORO_MODEL = ModelFile(
    "kokoro-v1.0.onnx",
    f"{_RELEASE}/kokoro-v1.0.onnx",
    "7d5df8ecf7d4b1878015a32686053fd0eebe2bc377234608764cc0ef3636a6c5",
)
KOKORO_VOICES = ModelFile(
    "voices-v1.0.bin",
    f"{_RELEASE}/voices-v1.0.bin",
    "bca610b8308e8d99f32e6fe4197e7ec01679264efed0cac9140fe9c29f1fbf7d",
)

PROVENANCE = {
    "engine": "Kokoro-82M via kokoro-onnx",
    "model": {"url": KOKORO_MODEL.url, "sha256": KOKORO_MODEL.sha256},
    "voices": {"url": KOKORO_VOICES.url, "sha256": KOKORO_VOICES.sha256},
    "licences": "weights Apache-2.0; kokoro-onnx MIT; espeak-ng/phonemizer GPL-3.0 (libraries only, not the audio)",
    "trainingDataNote": "The model card records training on synthetic audio generated by closed TTS models from large "
    "providers (research/rendered/kokoro-82m-model-card-2026-09-29.txt:241; RED-TEAM §2.12).",
}


def ensure_models(cache_dir: Path = CACHE_DIR / "models", opener=None) -> tuple[Path, Path]:
    """Download (or reuse) both model files, each verified against its pinned sha256."""
    cache_dir = Path(cache_dir)
    model = fetch(KOKORO_MODEL.url, KOKORO_MODEL.sha256, cache_dir / KOKORO_MODEL.filename, opener)
    voices = fetch(KOKORO_VOICES.url, KOKORO_VOICES.sha256, cache_dir / KOKORO_VOICES.filename, opener)
    return model, voices


# --- text: the fork's normalisation, kept byte-for-byte in behaviour -------------------------------------------

_SENTENCE_BREAK = re.compile(r"(?<=[.!?…])\s+|\n+")
_YEAR = re.compile(r"(?<![$\d,.])\b(1[1-9]|20)(\d{2})\b(?!\d|[.,]\d|\s?%|x\b|\s?dollars)")
_MONEY = re.compile(
    r"\$\s?(\d[\d,]*(?:\.\d+)?)"
    r"(?:\s?(million|billion|trillion|thousand)\b|([kKmMbB])(?:n)?\b)?"
)
_MONEY_SCALE = {"k": "thousand", "m": "million", "b": "billion"}


def normalize_english(text: str) -> str:
    """Spell out what espeak-ng misreads: "3.5%" is not "three. five percent", "2020" is not "two thousand twenty".

    Same rules as the fork's `normalize_kokoro_english`, with one widening: its year pattern covers 1100-1999
    (`1[1-9]`); the years here are 20xx, so `20` is accepted as a century too ("2020" -> "20 20", "2005" -> "20 oh 5").
    """

    def _year(m: re.Match) -> str:
        century, rest = m.group(1), m.group(2)
        if rest == "00":
            return f"{century} hundred" if century != "20" else "two thousand"
        if rest.startswith("0"):
            return f"{century} oh {rest[1]}"
        return f"{century} {rest}"

    def _money(m: re.Match) -> str:
        scale = m.group(2) or _MONEY_SCALE.get((m.group(3) or "").lower(), "")
        return f"{m.group(1)} {scale} dollars" if scale else f"{m.group(1)} dollars"

    text = _YEAR.sub(_year, text)
    text = _MONEY.sub(_money, text)
    text = re.sub(r"(\d)\s?%", r"\1 percent", text)
    text = re.sub(r"(\d)x\b", r"\1 times", text)
    text = re.sub(r"(\d+)\.(\d+)", lambda m: f"{m.group(1)} point {' '.join(m.group(2))}", text)
    return text


def apply_pronunciations(text: str, pronounce: dict[str, str]) -> str:
    """Spoken-only respellings from the spec (e.g. "IP" -> "I P"); subtitles keep the written word."""
    for written, spoken in pronounce.items():
        text = re.sub(rf"\b{re.escape(written)}\b", spoken, text)
    return text


def split_sentences(text: str) -> list[str]:
    return [s.strip() for s in _SENTENCE_BREAK.split(text) if s.strip()]


# --- audio -------------------------------------------------------------------------------------------------------


class Engine(Protocol):
    def create(self, text: str, voice: str, speed: float, lang: str) -> tuple[Any, int]: ...


def load_engine(model_path: Path, voices_path: Path) -> Engine:
    from kokoro_onnx import Kokoro

    return Kokoro(str(model_path), str(voices_path))


@dataclass(frozen=True)
class SentenceTiming:
    text: str  # as written: what the subtitle shows
    spoken: str  # what the model was given
    start: float  # seconds from the start of the scene
    end: float


@dataclass
class SceneAudio:
    samples: np.ndarray
    sample_rate: int
    fps: int
    sentences: list[SentenceTiming]

    @property
    def frames(self) -> int:
        spf = self.sample_rate // self.fps
        if len(self.samples) % spf:
            raise ValueError("scene audio is not a whole number of video frames")
        return len(self.samples) // spf

    @property
    def duration(self) -> float:
        """Exact: the audio is padded to whole frames, so frames / fps == samples / sample_rate."""
        return len(self.samples) / self.sample_rate


def synthesize_scene(engine: Engine, narration: str, voice: dict[str, Any], fps: int) -> SceneAudio:
    """Speak each sentence whole, pause between sentences, add the scene tail, pad to a whole number of frames."""
    sentences = split_sentences(narration)
    if not sentences:
        raise ValueError("a scene needs narration")
    pronounce = voice.get("pronounce", {})
    chunks: list[np.ndarray] = []
    timings: list[SentenceTiming] = []
    cursor = 0
    sr = 0
    for i, sentence in enumerate(sentences):
        spoken = normalize_english(apply_pronunciations(sentence, pronounce))
        samples, rate = engine.create(spoken, voice=voice["voice"], speed=float(voice["speed"]), lang=voice["lang"])
        samples = np.asarray(samples, dtype=np.float32).reshape(-1)
        if not samples.size:
            raise ValueError(f"Kokoro produced no audio for: {sentence!r}")
        if sr and rate != sr:
            raise ValueError(f"sample rate changed mid-scene: {sr} -> {rate}")
        sr = int(rate)
        timings.append(SentenceTiming(sentence, spoken, cursor / sr, (cursor + samples.size) / sr))
        chunks.append(samples)
        cursor += samples.size
        gap = float(voice["sentencePauseSeconds"]) if i < len(sentences) - 1 else float(voice["sceneTailSeconds"])
        pause = np.zeros(int(round(sr * gap)), dtype=np.float32)
        chunks.append(pause)
        cursor += pause.size
    if sr % fps:
        raise ValueError(f"sample rate {sr} is not a multiple of {fps} fps; frame-exact scenes need one")
    spf = sr // fps
    pad = (-cursor) % spf
    if pad:
        chunks.append(np.zeros(pad, dtype=np.float32))
    audio = np.clip(np.concatenate(chunks), -1.0, 1.0)
    return SceneAudio(audio, sr, fps, timings)


def write_wav(path: Path, samples: np.ndarray, sample_rate: int) -> None:
    """16-bit mono PCM through the standard library's wave module."""
    pcm = (np.clip(samples, -1.0, 1.0) * 32767.0).round().astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(int(sample_rate))
        w.writeframes(pcm.tobytes())
