"""Hebrew narration: Phonikud's rule-based G2P (CC BY 4.0) -> IPA -> Kokoro-82M (Apache-2.0) via kokoro-onnx (MIT).

Kokoro was never trained on Hebrew; it is driven with IPA phonemes, and no Hebrew speech dataset is used anywhere
in the chain. Runs on CPU, costs nothing, needs no network at run time. Adapted from the voice prototype of
28.9.2026 (scratchpad hebrew_tts.py), which chose the defaults on a held-out set and checked them on a fresh one.

INPUT CONTRACT - every line MUST be fully vowelised (nikud), with Phonikud's marks where its default is wrong:
  U+05BD meteg on a letter  = vocal shva       (לְֽהוֹרִים -> lehoʁˈim, not lhoʁˈim)
  U+05AB after a vowel      = stressed syllable (תּ֫וֹכֶן -> tˈoχen; the default is final stress)
  U+05C7 kamatz katan       = 'o'               (כׇל -> kˈol)
Unvowelised Hebrew phonemises to consonant strings (שלום -> ʃˈlm) and is refused. A line starting with "@" is raw
Kokoro IPA (a respelling), for a line that fails the ASR gate.

Model files: GitHub release thewh1teagle/kokoro-onnx model-files-v1.0, sha256-pinned (the same pins as
products/chart-explainer/tts.py). setup.sh downloads them into .cache/models; they are never committed.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
DEFAULT_MODELS = HERE / ".cache" / "models"
_RELEASE = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0"
MODEL = ("kokoro-v1.0.onnx", f"{_RELEASE}/kokoro-v1.0.onnx",
         "7d5df8ecf7d4b1878015a32686053fd0eebe2bc377234608764cc0ef3636a6c5")
VOICES = ("voices-v1.0.bin", f"{_RELEASE}/voices-v1.0.bin",
          "bca610b8308e8d99f32e6fe4197e7ec01679264efed0cac9140fe9c29f1fbf7d")

DEFAULT_VOICE = "ef_dora"  # picked on a held-out ASR round-trip, checked on a fresh set (prototype, 28.9.2026)
DEFAULT_SPEED = 0.9
SAMPLE_RATE = 24000

PROVENANCE = {
    "engine": "Kokoro-82M via kokoro-onnx 0.6.1, driven with Hebrew IPA from Phonikud 0.4.1 (rule-based G2P)",
    "model": {"file": MODEL[0], "url": MODEL[1], "sha256": MODEL[2]},
    "voices": {"file": VOICES[0], "url": VOICES[1], "sha256": VOICES[2]},
    "licences": {
        "kokoro_weights": "Apache-2.0 (research/rendered/kokoro-82m-model-card-2026-09-29.txt:53)",
        "kokoro_onnx": "MIT",
        "phonikud": "CC BY 4.0 - attribution: Phonikud by thewh1teagle, https://github.com/thewh1teagle/phonikud",
    },
    "hebrew_voice_note": "Kokoro has no Hebrew voice; it reads IPA. No Hebrew speech dataset is used.",
    "training_data_note": "The Kokoro model card records training on synthetic audio generated by closed TTS models "
                          "from large providers (research/rendered/kokoro-82m-model-card-2026-09-29.txt:241).",
    "ipa_mapping": "ʔ dropped, χ -> x, ʁ -> ɾ (each measured with a Whisper round-trip in the prototype)",
}

_HEB_LETTER = re.compile("[א-ת]")
_NIKUD = re.compile("[֑-ׇֽֿׁׂׅׄ]")


def kokoro_hebrew(ipa: str) -> str:
    """Map Phonikud IPA onto what Kokoro renders intelligibly: ʔ dropped (Kokoro turns it into t/d; Israeli speech
    mostly drops it), χ -> x (Kokoro turns χ into ʁ or l), ʁ -> ɾ (a tap is understood far better)."""
    return ipa.replace("ʔ", "").replace("χ", "x").replace("ʁ", "ɾ")


def require_vowelised(line: str) -> None:
    letters, marks = len(_HEB_LETTER.findall(line)), len(_NIKUD.findall(line))
    if letters and marks < letters * 0.5:
        raise ValueError(f"line looks unvowelised ({marks} nikud marks for {letters} letters): {line}")


def _sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def check_models(models_dir: Path) -> tuple[Path, Path]:
    out = []
    for name, url, want in (MODEL, VOICES):
        p = Path(models_dir) / name
        if not p.is_file():
            raise FileNotFoundError(f"missing {p}; run setup.sh (downloads {url})")
        got = _sha256(p)
        if got != want:
            raise ValueError(f"{p}: sha256 {got}, expected {want}")
        out.append(p)
    return out[0], out[1]


class Narrator:
    def __init__(self, models_dir: Path = DEFAULT_MODELS, voice: str = DEFAULT_VOICE, speed: float = DEFAULT_SPEED):
        from kokoro_onnx import Kokoro

        model, voices = check_models(models_dir)
        self.k = Kokoro(str(model), str(voices))
        self.voice, self.speed = voice, speed

    def ipa(self, line: str) -> str:
        if line.startswith("@"):
            return line[1:].strip()
        from phonikud import phonemize

        require_vowelised(line)
        return kokoro_hebrew(phonemize(line))

    def line(self, line: str) -> tuple[np.ndarray, str]:
        """One narration line -> (float32 samples at 24 kHz, the IPA it was read from)."""
        ipa = self.ipa(line)
        samples, sr = self.k.create(ipa, voice=self.voice, speed=self.speed, is_phonemes=True)
        if sr != SAMPLE_RATE:
            raise ValueError(f"unexpected sample rate {sr}")
        return np.asarray(samples, dtype=np.float32), ipa
