/**
 * Revenue Colony — the sweep workflow, generated from the criteria registry.
 *
 * The 112-scout sweep runs as a Workflow script, and a Workflow script cannot
 * import anything: it has no filesystem and no module access. Inlining the
 * criteria would therefore fork them from criteria.ts the first time either
 * changed. So the script is generated from the registry instead, and a test
 * asserts the checked-in file still matches what this renders. Drift becomes a
 * failing test rather than a silently stale search space.
 *
 * Regenerate with:  pnpm exec tsx scripts/gen-sweep-workflow.ts
 * Run with:         the Workflow tool, script = workflows/colony-criteria-sweep.js
 */

import { CRITERIA_GROUPS } from "./criteria.js";

/** Where the generated script lives, relative to the repo root. */
export const SWEEP_WORKFLOW_PATH = "workflows/colony-criteria-sweep.js";

const MISSION = [
  "MISSION (repo /home/user/automaton, MISSION.md is binding):",
  "- The owner does NOTHING. He does not talk to people, does not appear on camera, does not sell, does not do manual ops. Everything must be built and run by software agents.",
  "- Unavoidable exceptions are ONLY one-time identity/KYC/payout steps that a platform legally requires of a human. Catalogue those precisely as ownerBlockers; never invent extra ones; never assume they are done.",
  "- Target: 20,000 ILS/month, then 50,000 ILS/month, recorded in a ledger with real platform transaction ids. Projections are not revenue.",
  "- The owner is an Israeli resident. Payability to Israel is a hard gate: a line that cannot pay an Israeli is worth zero however good the idea.",
  "- Constitution: honest value only. No spam, no scams, no fake reviews, no engagement farming, no ToS violations, no deceiving a buyer. This outranks the revenue target.",
  "- Already shipped: products/il-biz-tools (free Hebrew calculators plus a small Pro tier via Paddle), products/telegram-il-tools-bot (Telegram Stars), products/apify-il-open-data (Apify pay-per-event), products/x402-il-api (paid API over x402).",
];

const SCOUT_RULES = [
  "RULES:",
  '1. Load web tools first: ToolSearch with query "select:WebSearch,WebFetch". curl will fail - the container has no outbound network - and so will most of WebFetch: the egress proxy blocks nearly every domain (paddle.com, dev.to, news.ycombinator.com and the rest all return EGRESS_BLOCKED). WebSearch works and returns snippets. WebFetch works for github.com. Plan for that: search widely, and do not waste turns re-trying a blocked host.',
  '2. Every finding needs at least one real URL you actually fetched or a search result you actually saw, with a date. Never invent a number, a price, a user count or a revenue figure. "unknown" is a valid, useful answer.',
  '2b. Say which kind of evidence each claim rests on. A rendered page is strong; a search snippet quoting that page is weaker and must be marked as such; your own memory is not evidence at all. When a claim matters and you could only get a snippet, list the exact URL a human or an unblocked agent must open to close it.',
  "3. Judge payability to Israel explicitly (YES / NO / UNKNOWN) with evidence. A NO is a first-class finding, not a failure.",
  "4. Judge ToS/legal risk: GREEN (clearly permitted), AMBER (unclear or restricted), RED (violates terms, law, or our constitution). Never recommend AMBER or RED as a build.",
  '5. Prefer things a software-only operation can ship in under 40 hours and that a specific, nameable buyer pays for. Say who the buyer is. "Everyone" means you have not found the buyer.',
  "6. Report dead ends. A criterion that is genuinely empty is worth knowing and saves the colony from re-searching it.",
  "7. Aim for at least 5 findings; if the criterion honestly yields fewer, say so in deadEnds rather than padding.",
  "8. WEB SEARCH IS A SHARED, FINITE BUDGET - roughly 200 calls for the whole session, across every agent running at once, and it is divided by the number of scouts running beside you, not by what you could usefully spend. Spend AT MOST 8, on the questions you cannot answer any other way. That number is deliberately low and it comes from a measured failure: in the first wave the early scouts spent 11-20 each and the later ones in the same wave found their searches refused, so a group nominally covered by 8 scouts was covered by 5.5. When early scouts burn the budget the later ones are structurally blind, and a blind scout that keeps a confident tone is worse than no scout: there is nothing underneath it. If your searches start being refused, say so in deadEnds, mark everything you had to infer as low confidence, and stop - do not fill the gap from memory.",
  "9. github.com and raw.githubusercontent.com DO render, and platforms check their own terms, policies, docs and pricing into public repos. Use them as primary sources wherever the answer lives in a repo. A rendered clause from a platform's own docs repo beats ten search snippets and costs no search budget. LEAD with GitHub code and repo search on Israeli criteria in particular: gov.il, btl.gov.il, kolzchut.org.il, data.gov.il, ica.justice.gov.il and every Israeli vendor domain are egress-blocked, so nine agents in one wave rendered zero primary Israeli sources and GitHub carried the entire group's best evidence. ONE MECHANIC THAT COSTS AGENTS A TURN EVERY WAVE: the GitHub MCP tools are scoped to this repo only - `get_file_contents` on any other repository is refused. Do not spend turns discovering that. Fetch other repos' files with WebFetch against raw.githubusercontent.com instead, which works and costs no search budget; `search_code` through the MCP does still reach across GitHub.",
];

const SCOUT_SCHEMA = {
  type: "object",
  properties: {
    criterion: { type: "string" },
    searchesRun: { type: "array", items: { type: "string" } },
    findings: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          whatItIs: { type: "string" },
          buyer: { type: "string", description: "the specific person or company that pays" },
          demandEvidence: { type: "string" },
          evidenceUrls: { type: "array", items: { type: "string" } },
          moneyModel: { type: "string" },
          pricePointIls: { type: "string" },
          monthlyCeilingIls: { type: "number", description: "honest ceiling for a no-brand new entrant" },
          buildHours: { type: "number" },
          ownerBlockers: { type: "array", items: { type: "string" } },
          israelPayable: { type: "string", enum: ["YES", "NO", "UNKNOWN"] },
          tosRisk: { type: "string", enum: ["GREEN", "AMBER", "RED"] },
          competition: { type: "string" },
          killCriteria: { type: "string" },
          confidence: { type: "string", enum: ["high", "medium", "low"] },
        },
        required: ["name", "whatItIs", "buyer", "demandEvidence", "evidenceUrls", "moneyModel", "monthlyCeilingIls", "buildHours", "israelPayable", "tosRisk", "confidence"],
      },
    },
    deadEnds: { type: "array", items: { type: "string" } },
  },
  required: ["criterion", "findings", "deadEnds"],
};

const RANKED_ITEM = {
  type: "object",
  properties: {
    name: { type: "string" },
    pitch: { type: "string" },
    buyer: { type: "string" },
    moneyModel: { type: "string" },
    monthlyCeilingIls: { type: "number" },
    buildHours: { type: "number" },
    ownerBlockers: { type: "array", items: { type: "string" } },
    israelPayable: { type: "string", enum: ["YES", "NO", "UNKNOWN"] },
    tosRisk: { type: "string", enum: ["GREEN", "AMBER", "RED"] },
    evidenceUrls: { type: "array", items: { type: "string" } },
    score: { type: "number", description: "0-100: evidence x payability x feasibility x margin" },
    whyThisRank: { type: "string" },
    firstStep: { type: "string", description: "the single next action a software agent takes" },
    killCriteria: { type: "string" },
  },
  required: ["name", "pitch", "buyer", "moneyModel", "monthlyCeilingIls", "buildHours", "israelPayable", "tosRisk", "score", "firstStep", "killCriteria"],
};

const SUPERVISOR_SCHEMA = {
  type: "object",
  properties: {
    group: { type: "string" },
    headline: { type: "string", description: "one honest sentence: is there money in this group at all?" },
    ranked: { type: "array", description: "at most 6, best first", items: RANKED_ITEM },
    rejected: {
      type: "array",
      items: {
        type: "object",
        properties: { name: { type: "string" }, reason: { type: "string" } },
        required: ["name", "reason"],
      },
    },
    ownerBlockersFound: { type: "array", items: { type: "string" } },
    scoutsWeak: { type: "array", items: { type: "string" }, description: "criteria whose scout returned thin or unsourced work" },
  },
  required: ["group", "headline", "ranked", "rejected", "ownerBlockersFound"],
};

const AUDIT_SCHEMA = {
  type: "object",
  properties: {
    group: { type: "string" },
    verdicts: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          verdict: { type: "string", enum: ["CONFIRMED", "DOWNGRADED", "REFUTED"] },
          why: { type: "string" },
          correctedCeilingIls: { type: "number" },
          correctedIsraelPayable: { type: "string", enum: ["YES", "NO", "UNKNOWN"] },
          unsupportedClaims: { type: "array", items: { type: "string" } },
        },
        required: ["name", "verdict", "why"],
      },
    },
    supervisorErrors: { type: "array", items: { type: "string" } },
    missedAngles: { type: "array", items: { type: "string" } },
  },
  required: ["group", "verdicts", "supervisorErrors", "missedAngles"],
};

const CHIEF_SCHEMA = {
  type: "object",
  properties: {
    auditorsWhoRubberStamped: { type: "array", items: { type: "string" } },
    survivingCandidates: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          group: { type: "string" },
          correctedCeilingIls: { type: "number" },
          israelPayable: { type: "string", enum: ["YES", "NO", "UNKNOWN"] },
          tosRisk: { type: "string", enum: ["GREEN", "AMBER", "RED"] },
          evidenceQuality: { type: "string", enum: ["strong", "adequate", "thin"] },
          why: { type: "string" },
        },
        required: ["name", "group", "correctedCeilingIls", "israelPayable", "tosRisk", "evidenceQuality", "why"],
      },
    },
    systemicProblems: { type: "array", items: { type: "string" } },
    ownerBlockerCatalogue: { type: "array", items: { type: "string" } },
  },
  required: ["survivingCandidates", "systemicProblems", "ownerBlockerCatalogue"],
};

const BOARD_SCHEMA = {
  type: "object",
  properties: {
    verdict: { type: "string", description: "the honest one-paragraph answer to: can this portfolio reach 20,000 ILS/month, and by when?" },
    buildNow: {
      type: "array",
      description: "at most 8 lines to build immediately, in order",
      items: {
        type: "object",
        properties: {
          lineId: { type: "string", description: "kebab-case id suitable for src/revenue/portfolio.ts" },
          nameHe: { type: "string" },
          nameEn: { type: "string" },
          thesis: { type: "string" },
          buyer: { type: "string" },
          moneyModel: { type: "string" },
          targetMonthlyIls: { type: "number" },
          firstStep: { type: "string" },
          buildHours: { type: "number" },
          ownerSetup: { type: "array", items: { type: "string" } },
          killCriteria: { type: "string" },
          scaleCriteria: { type: "string" },
          evidenceUrls: { type: "array", items: { type: "string" } },
        },
        required: ["lineId", "nameHe", "nameEn", "thesis", "buyer", "moneyModel", "targetMonthlyIls", "firstStep", "buildHours", "ownerSetup", "killCriteria", "scaleCriteria"],
      },
    },
    changeExisting: {
      type: "array",
      description: "changes to the lines already in src/revenue/portfolio.ts",
      items: {
        type: "object",
        properties: {
          lineId: { type: "string" },
          action: { type: "string", enum: ["keep", "retarget", "pivot", "kill"] },
          newTargetIls: { type: "number" },
          why: { type: "string" },
        },
        required: ["lineId", "action", "why"],
      },
    },
    rejectedWithReasons: {
      type: "array",
      items: {
        type: "object",
        properties: { name: { type: "string" }, reason: { type: "string" } },
        required: ["name", "reason"],
      },
    },
    ownerChecklist: {
      type: "array",
      description: "the complete ordered list of one-time human steps, shortest possible",
      items: {
        type: "object",
        properties: { step: { type: "string" }, platform: { type: "string" }, unlocksIls: { type: "number" }, minutes: { type: "number" } },
        required: ["step", "platform", "unlocksIls"],
      },
    },
    repoAdditions: {
      type: "array",
      description: "concrete things to add to this repo: skills, agents, tests, watchdogs, tools",
      items: {
        type: "object",
        properties: { path: { type: "string" }, what: { type: "string" }, why: { type: "string" }, priority: { type: "string", enum: ["P0", "P1", "P2"] } },
        required: ["path", "what", "why", "priority"],
      },
    },
    pathTo20k: { type: "string", description: "the arithmetic: which lines, what each contributes, over what period" },
  },
  required: ["verdict", "buildNow", "changeExisting", "rejectedWithReasons", "ownerChecklist", "repoAdditions", "pathTo20k"],
};

const j = (value: unknown): string => JSON.stringify(value, null, 2);

/**
 * Render the workflow script. Deliberately emits no template literals of its
 * own — every prompt is built by array join and concatenation — so that this
 * renderer stays readable and the output stays diffable.
 */
export function renderSweepWorkflow(): string {
  const groups = CRITERIA_GROUPS.map((g) => ({
    id: g.id,
    title: g.title,
    criteria: g.criteria.map((c) => [c.id.slice(g.id.length + 1), c.brief]),
  }));
  const scoutCount = CRITERIA_GROUPS.reduce((n, g) => n + g.criteria.length, 0);

  return [
    "// GENERATED FILE - do not edit by hand.",
    "// Source of truth: src/revenue/criteria.ts (the criteria) and",
    "// src/revenue/sweep-workflow.ts (the prompts and schemas).",
    "// Regenerate: pnpm exec tsx scripts/gen-sweep-workflow.ts",
    "//",
    "// The revenue colony's chain of command, run as one workflow:",
    "//   " + scoutCount + " scouts (one per criterion) -> " + CRITERIA_GROUPS.length + " supervisors (one per group)",
    "//   -> " + CRITERIA_GROUPS.length + " auditors (one per supervisor) -> chief auditor -> board.",
    "",
    "export const meta = {",
    "  name: 'colony-criteria-sweep',",
    "  description: '" + scoutCount + " scout agents search one income criterion each; a supervisor per criterion group, an auditor per supervisor, then chief auditor and board',",
    "  phases: [",
    "    { title: 'Scouts', detail: '" + scoutCount + " workers, one per criterion, across " + CRITERIA_GROUPS.length + " groups' },",
    "    { title: 'Supervisors', detail: 'one supervisor per criterion group: dedupe, score, reject' },",
    "    { title: 'Auditors', detail: 'one auditor per group, adversarially refuting the supervisor' },",
    "    { title: 'Board', detail: 'chief auditor then board: portfolio decisions' },",
    "  ],",
    "}",
    "",
    "const MISSION = " + j(MISSION) + ".join('\\n')",
    "",
    "const SCOUT_RULES = " + j(SCOUT_RULES) + ".join('\\n')",
    "",
    "const SCOUT_SCHEMA = " + j(SCOUT_SCHEMA),
    "",
    "const SUPERVISOR_SCHEMA = " + j(SUPERVISOR_SCHEMA),
    "",
    "const AUDIT_SCHEMA = " + j(AUDIT_SCHEMA),
    "",
    "const CHIEF_SCHEMA = " + j(CHIEF_SCHEMA),
    "",
    "const BOARD_SCHEMA = " + j(BOARD_SCHEMA),
    "",
    "const ALL_GROUPS = " + j(groups),
    "",
    "// Waves. A full fan-out of " + (scoutCount + CRITERIA_GROUPS.length * 2 + 2) + " agents does not fit inside one usage",
    "// window - the first full run died on the session limit with 123 of 128 agents",
    "// unstarted. So the sweep is resumable by design:",
    "//   args = { groups: ['storefronts', 'payment-rails'] }  sweep those groups only",
    "//   args = { board: true }                               judge what is already on disk",
    "//   args omitted                                          the full run",
    "// In wave mode the board is skipped: it decides across ALL groups, not a slice.",
    "//",
    "// `exclude` drops individual criteria from the fan-out:",
    "//   args = { groups: ['storefronts'], exclude: ['storefronts/gumroad'] }",
    "// A workflow script has no filesystem, so it cannot see which criteria already",
    "// have a scout report - the caller passes them. This is not an optimisation:",
    "// re-running a swept criterion spends 8 searches out of a ~200-call session",
    "// budget shared by every agent, so a wave that redoes five of its eight",
    "// criteria makes the three that matter blind. Get the list with",
    "// `colony criteria --json` or from research/colony-sweep/scouts/.",
    "// An excluded criterion's scout does NOT run, so its report is not in the",
    "// supervisor's input either - only the reports on disk. The supervisor prompt",
    "// therefore names the directory and tells it to read the group's other reports",
    "// itself. Without that step a wave would silently narrow the group it judges.",
    "const WAVE = Array.isArray(args) ? { groups: args } : (args || {})",
    "const BOARD_ONLY = WAVE.board === true",
    "const EXCLUDE = Array.isArray(WAVE.exclude) ? WAVE.exclude : []",
    "const GROUPS = (BOARD_ONLY ? [] : (WAVE.groups && WAVE.groups.length",
    "  ? ALL_GROUPS.filter((g) => WAVE.groups.indexOf(g.id) !== -1)",
    "  : ALL_GROUPS))",
    "  .map((g) => ({ ...g, criteria: g.criteria.filter((c) => EXCLUDE.indexOf(g.id + '/' + c[0]) === -1) }))",
    "  .filter((g) => g.criteria.length > 0)",
    "if (!BOARD_ONLY && GROUPS.length === 0) throw new Error('no criterion group matched args.groups, or exclude emptied every one')",
    "",
    "const scoutPrompt = (g, c) => [",
    "  'You are WORKER-SCOUT \"' + c[0] + '\" reporting to the supervisor of the \"' + g.id + '\" group in the revenue colony chain of command.',",
    "  '',",
    "  MISSION,",
    "  '',",
    "  'YOUR GROUP: ' + g.title,",
    "  'YOUR CRITERION - search this and only this, exhaustively:',",
    "  c[1],",
    "  '',",
    "  SCOUT_RULES,",
    "  '',",
    "  'OUTPUT: also write your full notes, with every URL you used, to /home/user/automaton/research/colony-sweep/scouts/' + g.id + '--' + c[0] + '.md (create the directory first with mkdir -p). Then return the structured result. Do not edit any other file in the repo.',",
    "].join('\\n')",
    "",
    "const supervisorPrompt = (g, scouts) => [",
    "  'You are the SUPERVISOR of the \"' + g.id + '\" criterion group in the revenue colony chain of command. ' + g.criteria.length + ' scouts reported to you.',",
    "  '',",
    "  MISSION,",
    "  '',",
    "  'GROUP: ' + g.title,",
    "  '',",
    "  'SCOUT REPORTS FROM THIS WAVE (JSON):',",
    "  JSON.stringify(scouts.filter(Boolean), null, 1).slice(0, 120000),",
    "  '',",
    "  'BEFORE YOU START - READ THE REST OF YOUR GROUP FROM DISK.',",
    "  'Your group has ' + g.criteria.length + ' criteria in this wave, but the group as a whole may have more: criteria swept in an earlier wave are deliberately excluded from the fan-out so they do not spend the shared search budget twice. Their reports are on disk at /home/user/automaton/research/colony-sweep/scouts/, named ' + g.id + '--<criterion>.md. List that directory, read every file matching your group, and treat those reports as scout input exactly like the JSON above. A group report written from this wave alone would be judging a slice while claiming to judge the group.',",
    "  '',",
    "  'YOUR JOB:',",
    "  '1. Merge and deduplicate across your scouts. The same opportunity often appears under several criteria; keep the best-evidenced version.',",
    "  '2. Verify before you promote: spot-check the strongest claims with WebSearch/WebFetch (load them via ToolSearch \"select:WebSearch,WebFetch\"). A finding with no real URL, or a number no source supports, must be demoted or rejected - say so.',",
    "  '3. Reject ruthlessly: anything not payable to Israel, anything AMBER or RED on terms, anything needing the owner to talk to a human, anything that cannot be built by software alone, and anything whose honest ceiling is under 300 ILS/month.',",
    "  '4. Score the survivors 0-100 on evidence strength x Israel payability x build feasibility x margin, and rank them. At most 6 survive.',",
    "  '5. For each survivor give the single concrete first step a software agent would take - not a plan, one action.',",
    "  '6. Name the scouts whose work was thin or unsourced. Your auditor will check whether you were honest about this.',",
    "  '',",
    "  'Write your group report to /home/user/automaton/research/colony-sweep/groups/' + g.id + '.md (mkdir -p first), including the rejected list and why. Then return the structured result. Do not edit any other file.',",
    "].join('\\n')",
    "",
    "const auditorPrompt = (g, sup) => [",
    "  'You are the AUDITOR assigned to the \"' + g.id + '\" group. You do not report to its supervisor; you check it. Your job is to REFUTE, not to agree.',",
    "  '',",
    "  MISSION,",
    "  '',",
    "  'THE SUPERVISOR REPORT (JSON):',",
    "  JSON.stringify(sup, null, 1).slice(0, 100000),",
    "  '',",
    "  'FOR EACH RANKED CANDIDATE:',",
    "  '- Open the cited evidence yourself (ToolSearch \"select:WebSearch,WebFetch\"). If a URL does not support the claim, or does not exist, say so explicitly.',",
    "  '- Attack the Israel payability claim hardest. This is where optimism kills a line: a marketplace that serves Israeli buyers may not pay Israeli sellers.',",
    "  '- Attack the monthly ceiling. Ask what a brand-new entrant with no audience, no reviews and no backlinks earns in month one, not what the market leader earns.',",
    "  '- Attack the build estimate and the claim that no human is needed.',",
    "  '- Verdict CONFIRMED only if the evidence genuinely holds. DOWNGRADED if real but overstated - give the corrected numbers. REFUTED if it does not survive.',",
    "  '- Default to scepticism: if you cannot verify it, it is not CONFIRMED.',",
    "  '',",
    "  'Also list the supervisor own errors, and the angles the group missed entirely.',",
    "  '',",
    "  'Write your audit to /home/user/automaton/research/colony-sweep/audits/' + g.id + '.md (mkdir -p first). Then return the structured result. Do not edit any other file.',",
    "].join('\\n')",
    "",
    "// The loop: scouts -> supervisor -> auditor, per group, with no barrier between groups.",
    "phase('Scouts')",
    "log(BOARD_ONLY",
    "  ? 'Board wave: judging the group reports already on disk, no scouts.'",
    "  : 'Chain of command: ' + GROUPS.length + '/' + ALL_GROUPS.length + ' criterion groups, ' +",
    "    GROUPS.reduce((n, g) => n + g.criteria.length, 0) + ' scouts, one supervisor and one auditor per group.')",
    "",
    "const groupResults = await pipeline(",
    "  GROUPS,",
    "  (g) => parallel(g.criteria.map((c) => () => agent(scoutPrompt(g, c), {",
    "    label: 'scout:' + g.id + '/' + c[0],",
    "    phase: 'Scouts',",
    "    schema: SCOUT_SCHEMA,",
    "    agentType: 'general-purpose',",
    "    model: 'opus',",
    "    effort: 'medium',",
    "  }))),",
    "  (scouts, g) => agent(supervisorPrompt(g, scouts || []), {",
    "    label: 'supervisor:' + g.id,",
    "    phase: 'Supervisors',",
    "    schema: SUPERVISOR_SCHEMA,",
    "    agentType: 'general-purpose',",
    "    model: 'opus',",
    "    effort: 'high',",
    "  }),",
    "  (sup, g) => (sup",
    "    ? agent(auditorPrompt(g, sup), {",
    "        label: 'auditor:' + g.id,",
    "        phase: 'Auditors',",
    "        schema: AUDIT_SCHEMA,",
    "        agentType: 'general-purpose',",
    "        model: 'opus',",
    "        effort: 'high',",
    "      }).then((audit) => ({ group: g.id, title: g.title, supervisor: sup, audit }))",
    "    : { group: g.id, title: g.title, supervisor: null, audit: null }),",
    ")",
    "",
    "const groups = groupResults.filter(Boolean)",
    "log(groups.length + '/' + GROUPS.length + ' groups completed the supervisor and auditor stages.')",
    "",
    "phase('Board')",
    "",
    "// A wave stops here: partial groups are not a portfolio, and a board that",
    "// decides on a slice would be deciding without the evidence it needs.",
    "if (!BOARD_ONLY && WAVE.groups && WAVE.groups.length) {",
    "  log('Wave complete. Run again with args = { board: true } once every group has been swept.')",
    "  return { wave: WAVE.groups, groupsCompleted: groups.length, groupHeadlines: groups.map((r) => ({ group: r.group, headline: r.supervisor && r.supervisor.headline })) }",
    "}",
    "",
    "const chief = await agent([",
    "  'You are the CHIEF AUDITOR of the revenue colony. Each supervisor was checked by an auditor. You check the auditors.',",
    "  '',",
    "  MISSION,",
    "  '',",
    "  (BOARD_ONLY",
    "    ? 'THIS IS A BOARD-ONLY WAVE. The group reports are on disk, not in this prompt. Read every file in /home/user/automaton/research/colony-sweep/groups/ and /home/user/automaton/research/colony-sweep/audits/ before you judge anything, and say which groups are missing entirely - a missing group is an unsearched part of the space, not an empty one.'",
    "    : 'ALL GROUP RESULTS (supervisor rankings and their audits, JSON):'),",
    "  (BOARD_ONLY ? '' : JSON.stringify(groups.map((r) => ({ group: r.group, ranked: r.supervisor && r.supervisor.ranked, headline: r.supervisor && r.supervisor.headline, audit: r.audit })), null, 1).slice(0, 250000)),",
    "  '',",
    "  'YOUR JOB:',",
    "  '1. Find auditors who rubber-stamped: every verdict CONFIRMED, no corrections, no missed angles. Name them.',",
    "  '2. Build the single cross-group list of candidates that survive honest scrutiny, with the AUDITOR-corrected numbers, never the supervisor originals.',",
    "  '3. Drop duplicates that appear in several groups, keeping the best-evidenced framing.',",
    "  '4. Name the systemic problems in this sweep - where the whole fleet was optimistic, where evidence was thin, what nobody searched.',",
    "  '5. Consolidate every owner blocker found anywhere into one deduplicated catalogue. This is the shortest possible list of things the human must do, and it must not grow by invention.',",
    "  '',",
    "  'Write your report to /home/user/automaton/research/colony-sweep/CHIEF-AUDIT.md (mkdir -p first). Then return the structured result.',",
    "].join('\\n'), {",
    "  label: 'chief-auditor',",
    "  phase: 'Board',",
    "  schema: CHIEF_SCHEMA,",
    "  agentType: 'general-purpose',",
    "  model: 'fable',",
    "  effort: 'high',",
    "})",
    "",
    "const board = await agent([",
    "  'You are the BOARD of the revenue colony. You decide where effort and money go. Everything below has already been searched by " + scoutCount + " scouts, ranked by " + CRITERIA_GROUPS.length + " supervisors, attacked by " + CRITERIA_GROUPS.length + " auditors and re-checked by the chief auditor.',",
    "  '',",
    "  MISSION,",
    "  '',",
    "  'CHIEF AUDITOR REPORT (JSON):',",
    "  JSON.stringify(chief, null, 1).slice(0, 120000),",
    "  '',",
    "  (BOARD_ONLY",
    "    ? 'The group rankings are on disk: read /home/user/automaton/research/colony-sweep/groups/ and /home/user/automaton/research/colony-sweep/audits/.'",
    "    : 'GROUP HEADLINES AND RANKINGS (JSON):'),",
    "  (BOARD_ONLY ? '' : JSON.stringify(groups.map((r) => ({ group: r.group, headline: r.supervisor && r.supervisor.headline, ranked: r.supervisor && r.supervisor.ranked })), null, 1).slice(0, 180000)),",
    "  '',",
    "  'Read src/revenue/portfolio.ts and docs/INCOME_PLAN.he.md before deciding: they hold the lines that already exist.',",
    "  '',",
    "  'YOUR JOB:',",
    "  '1. Decide what gets built now, in order. At most 8. Each must be buildable by software alone and payable to an Israeli.',",
    "  '2. Decide what happens to each existing line: keep, retarget, pivot or kill, with the reason.',",
    "  '3. Write the path to 20,000 ILS/month as arithmetic, not as hope. If the honest answer is that this portfolio cannot get there, say so plainly and say what would be needed instead. The owner has explicitly asked for seriousness over comfort.',",
    "  '4. Produce the shortest possible ordered owner checklist - every one-time human step, what it unlocks in shekels, and how many minutes it takes. Do not invent steps. Do not include anything the software can do itself.',",
    "  '5. List concrete additions to this repo - skills, agents, tests, watchdogs, tools - with paths and priorities.',",
    "  '',",
    "  'Write the full board decision to /home/user/automaton/research/colony-sweep/BOARD.md (mkdir -p first), in English, with a Hebrew executive summary at the top for the owner. Then return the structured result.',",
    "].join('\\n'), {",
    "  label: 'board',",
    "  phase: 'Board',",
    "  schema: BOARD_SCHEMA,",
    "  agentType: 'general-purpose',",
    "  model: 'fable',",
    "  effort: 'high',",
    "})",
    "",
    "return {",
    "  scoutsRun: GROUPS.reduce((n, g) => n + g.criteria.length, 0),",
    "  groupsCompleted: groups.length,",
    "  groupHeadlines: groups.map((r) => ({ group: r.group, headline: r.supervisor && r.supervisor.headline, top: ((r.supervisor && r.supervisor.ranked) || []).slice(0, 3).map((x) => x.name) })),",
    "  chief,",
    "  board,",
    "}",
    "",
  ].join("\n");
}
